steps:
  - label: ":docker: Build & Push"
    key: build
    command: "bash scripts/build-and-push.sh"

  - label: ":rocket: Deploy to Fargate"
    key: deploy
    depends_on: build
    command: "bash scripts/deploy.sh"
